version: '3'
services:
  database:
    image: postgres:9.5.18
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gis_support
      - POSTGRES_DB=gis_support
    ports:
      - 5432:5433
  flask:
      build: .
      volumes:
        - ../. :/usr/src/app
      depends_on:
        - database
      ports:
      - 8000:5000
