version: '3.3'

services:
  flask:
    container_name: flask-api
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    command: wait4db
    environment:
      FLASK_DEBUG: "on"
    volumes:
      - ./:/usr/src/app
    restart: always
    ports:
      - 80:4444
    env_file:
      - ./.env
    depends_on:
    - database
  
  database:
    container_name: db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=gis_support
      - POSTGRES_DBNAME=gis_support
    ports:
      - 6666:5432
 
        
